[0;33m--- Warning: GDB cannot open serial ports accessed as COMx[0m
[0;33m--- Using \\.\COM22 instead...[0m
[0;33m--- esp-idf-monitor 1.5.0 on \\.\COM22 115200[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H[0m
[0;33m--- 0x4004c0d8: uart_tx_one_char_uart.part.0 in ROM
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038236c: check_trans_valid at C:/esp/esp-idf/v5.1.5/esp-idf/components/driver/spi/gpspi/spi_master.c:764 (discriminator 2)
0x40382ba2: spi_device_polling_start at C:/esp/esp-idf/v5.1.5/esp-idf/components/driver/spi/gpspi/spi_master.c:1041 (discriminator 2)
[0m
[0;33m--- 0x40380001: _vector_table at ??:?
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\hario\\OneDrive\\Desktop\\EPDTEST2\\build\\EPDTEST2.elf', '-ex', 'target remote | "c:\\esp\\tools\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\hario\\AppData\\Local\\Temp\\tmpfs8z56p_"', '-ex', 'bt']' returned non-zero exit status 1.
b"error starting child process '| c:\\esp\\tools\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\hario\\AppData\\Local\\Temp\\tmpfs8z56p_': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40048b82: software_reset in ROM
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038236c: check_trans_valid at C:/esp/esp-idf/v5.1.5/esp-idf/components/driver/spi/gpspi/spi_master.c:764 (discriminator 2)
0x40382ba2: spi_device_polling_start at C:/esp/esp-idf/v5.1.5/esp-idf/components/driver/spi/gpspi/spi_master.c:1041 (discriminator 2)
[0m
[0;33m--- 0x40380001: _vector_table at ??:?
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\hario\\OneDrive\\Desktop\\EPDTEST2\\build\\EPDTEST2.elf', '-ex', 'target remote | "c:\\esp\\tools\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\hario\\AppData\\Local\\Temp\\tmpoom11sgb"', '-ex', 'bt']' returned non-zero exit status 1.
b"error starting child process '| c:\\esp\\tools\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\hario\\AppData\\Local\\Temp\\tmpoom11sgb': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40048b82: software_reset in ROM
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038236c: check_trans_valid at C:/esp/esp-idf/v5.1.5/esp-idf/components/driver/spi/gpspi/spi_master.c:764 (discriminator 2)
0x40382ba2: spi_device_polling_start at C:/esp/esp-idf/v5.1.5/esp-idf/components/driver/spi/gpspi/spi_master.c:1041 (discriminator 2)
[0m
[0;33m--- 0x40380001: _vector_table at ??:?
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\hario\\OneDrive\\Desktop\\EPDTEST2\\build\\EPDTEST2.elf', '-ex', 'target remote | "c:\\esp\\tools\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\hario\\AppData\\Local\\Temp\\tmplxoq5gse"', '-ex', 'bt']' returned non-zero exit status 1.
b"error starting child process '| c:\\esp\\tools\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\hario\\AppData\\Local\\Temp\\tmplxoq5gse': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40048b82: software_reset in ROM
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038236c: check_trans_valid at C:/esp/esp-idf/v5.1.5/esp-idf/components/driver/spi/gpspi/spi_master.c:764 (discriminator 2)
0x40382ba2: spi_device_polling_start at C:/esp/esp-idf/v5.1.5/esp-idf/components/driver/spi/gpspi/spi_master.c:1041 (discriminator 2)
[0m
[0;33m--- 0x40380001: _vector_table at ??:?
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\hario\\OneDrive\\Desktop\\EPDTEST2\\build\\EPDTEST2.elf', '-ex', 'target remote | "c:\\esp\\tools\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\hario\\AppData\\Local\\Temp\\tmp9rlwp7c7"', '-ex', 'bt']' returned non-zero exit status 1.
b"error starting child process '| c:\\esp\\tools\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\hario\\AppData\\Local\\Temp\\tmp9rlwp7c7': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40048b82: software_reset in ROM
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038236c: check_trans_valid at C:/esp/esp-idf/v5.1.5/esp-idf/components/driver/spi/gpspi/spi_master.c:764 (discriminator 2)
0x40382ba2: spi_device_polling_start at C:/esp/esp-idf/v5.1.5/esp-idf/components/driver/spi/gpspi/spi_master.c:1041 (discriminator 2)
[0m
[0;33m--- 0x40380001: _vector_table at ??:?
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\hario\\OneDrive\\Desktop\\EPDTEST2\\build\\EPDTEST2.elf', '-ex', 'target remote | "c:\\esp\\tools\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\hario\\AppData\\Local\\Temp\\tmpx914o72t"', '-ex', 'bt']' returned non-zero exit status 1.
b"error starting child process '| c:\\esp\\tools\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\hario\\AppData\\Local\\Temp\\tmpx914o72t': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40048b82: software_reset in ROM
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038236c: check_trans_valid at C:/esp/esp-idf/v5.1.5/esp-idf/components/driver/spi/gpspi/spi_master.c:764 (discriminator 2)
0x40382ba2: spi_device_polling_start at C:/esp/esp-idf/v5.1.5/esp-idf/components/driver/spi/gpspi/spi_master.c:1041 (discriminator 2)
[0m
[0;33m--- 0x40380001: _vector_table at ??:?
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\hario\\OneDrive\\Desktop\\EPDTEST2\\build\\EPDTEST2.elf', '-ex', 'target remote | "c:\\esp\\tools\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\hario\\AppData\\Local\\Temp\\tmpik2gk835"', '-ex', 'bt']' returned non-zero exit status 1.
b"error starting child process '| c:\\esp\\tools\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\hario\\AppData\\Local\\Temp\\tmpik2gk835': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40048b82: software_reset in ROM
[0m
[0;33m--- Stack dump detected[0m
[0;33m--- 0x4038236c: check_trans_valid at C:/esp/esp-idf/v5.1.5/esp-idf/components/driver/spi/gpspi/spi_master.c:764 (discriminator 2)
0x40382ba2: spi_device_polling_start at C:/esp/esp-idf/v5.1.5/esp-idf/components/driver/spi/gpspi/spi_master.c:1041 (discriminator 2)
[0m
[0;33m--- 0x40380001: _vector_table at ??:?
[0m
[0;33m--- Warning: Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\hario\\OneDrive\\Desktop\\EPDTEST2\\build\\EPDTEST2.elf', '-ex', 'target remote | "c:\\esp\\tools\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\hario\\AppData\\Local\\Temp\\tmpcu1ibdhx"', '-ex', 'bt']' returned non-zero exit status 1.
b"error starting child process '| c:\\esp\\tools\\python_env\\idf5.1_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\hario\\AppData\\Local\\Temp\\tmpcu1ibdhx': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m--- 0x40048b82: software_reset in ROM
[0m
[0m
